# Generated by Django 2.1.2 on 2018-11-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
