# Generated by Django 2.1.2 on 2018-11-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_auto_20181122_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
