# Generated by Django 2.1.3 on 2018-12-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0009_remove_choice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, null=True, related_name='question', to='pools.Choice'),
        ),
    ]
