# Generated by Django 2.1.3 on 2018-12-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0010_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='question', to='pools.Choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
